// Generated by CoffeeScript 1.6.1
(function() {
  var F, cns, ctx, img, overlap, size, x, y;

  cns = document.getElementById('canvas');

  ctx = cns.getContext('2d');

  x = 0;

  y = 0;

  img = new Image();

  img.src = 'bear.jpg';

  size = 5;

  overlap = 10;

  F = 0.01;

  ctx.fillStyle = '#fff';

  cns.onmousemove = function(e) {
    x = e.offsetX;
    return y = e.offsetY;
  };

  img.onload = function() {
    var bearticles, draw, tickling, _i, _j, _ref, _ref1;
    ctx.drawImage(img, 0, 0);
    bearticles = [];
    for (x = _i = 0, _ref = img.width; size > 0 ? _i <= _ref : _i >= _ref; x = _i += size) {
      for (y = _j = 0, _ref1 = img.height; size > 0 ? _j <= _ref1 : _j >= _ref1; y = _j += size) {
        bearticles.push({
          x: x + 0.5 * (cns.width - img.width),
          y: y + 0.5 * (cns.height - img.height),
          imgData: ctx.getImageData(x - 0.5 * overlap, y - 0.5 * overlap, size + overlap, size + overlap)
        });
      }
    }
    ctx.fillRect(0, 0, cns.width, cns.height);
    tickling = function(bear) {
      var dx, dy, s;
      dx = x - bear.x;
      dy = y - bear.y;
      s = Math.sqrt(dx * dx + dy * dy);
      s *= F;
      s = Math.max(1, s);
      return ctx.putImageData(bear.imgData, bear.x - dx / s, bear.y - dy / s);
    };
    ctx.fillStyle = 'rgba(255, 255, 255, 1)';
    draw = function() {
      var bear, _k, _len, _results;
      ctx.fillRect(0, 0, cns.width, cns.height);
      _results = [];
      for (_k = 0, _len = bearticles.length; _k < _len; _k++) {
        bear = bearticles[_k];
        _results.push(tickling(bear));
      }
      return _results;
    };
    return setInterval(draw, 25);
  };

}).call(this);
