// Generated by CoffeeScript 1.6.1
(function() {
  var message;

  message = "Ready for your first Great Very-bear Adventure?";

  alert(message);

  message = "...Are you sure?";

  alert(message);

}).call(this);
