// Generated by CoffeeScript 1.6.1
(function() {
  var cns, ctx, draw, img, message, x, y;

  message = "Ready for your first Great Very-bear Adventure?";

  alert(message);

  cns = document.getElementById('canvas');

  ctx = cns.getContext('2d');

  x = 0;

  y = 0;

  img = new Image();

  img.src = 'http://upload.wikimedia.org/wikipedia/commons/7/77/NROL10_USA155_patch.jpg';

  ctx.fillStyle = '#000000';

  draw = function() {
    ctx.fillRect(0, 0, cns.width, cns.height);
    ctx.drawImage(img, x, y);
    x = x < cns.width ? x + cns.width / 100 : -img.width;
    return y = y < cns.height ? y + cns.height / 100 : -img.width * cns.height / cns.width;
  };

  setInterval(draw, 25);

}).call(this);
